### ISSUE TITLE
Create tag-specific feed?

### ISSUE THREAD

**Issue by amirmc** [kayceesrk/kayceesrk.github.io#1]
Not sure if you're planning to only post about OCaml things.  If so, then it doesn't matter.

I'd like to add it to https://github.com/ocaml/ocaml.org/blob/master/planet_feeds.txt

**Comment by kayceesrk** [comment]
Done. https://github.com/ocamllabs/ocl-reporter/pull/52.

**Comment by amirmc** [comment]
Thx! Also added to main feed in https://github.com/ocaml/ocaml.org/commit/f08bc6c2c5e289ba793b29f6a6b3bf865e987f8a

**Comment by kayceesrk** [comment]
Thanks very much!
